# Site settings
title: "PHP THINKTANK"
header-img: img/default.jpg
email: mjls@web.de
description: "We are a group of people which are developing concepts and framework agnostic components for the php world."
baseurl: ""
url: "http://marco-bunde.de"
twitter_username: makk_eightbit
github_username:  phpthinktank
facebook_username:  marco.bunge.dev

# Gems
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "assets/components/AdminLTE/pages", "_draft"]
